version: '3'

services:
  webserver:
    image: php:apache
    ports: 
      - '80:80'
    volumes:
      - ./website:/var/www/html

        #  python:
        #    image: python
        #    ports: # TODO
        #    volumes:
        #      - # TODO

